export const authors = [
  [
    1,
    'Pravin Mohan',
    'California Institute of Technology',
    '1990-06-30',
    10,
    'm',
    5,
  ],
  [
    2,
    'Taisa Shelley',
    'Massachusetts Institute of Technology',
    '1992-03-13',
    5,
    'f',
    9,
  ],
  [3, 'Uther Carlman', 'University of Chicago', '1986-02-05', 3, 'm', 1],

  [4, 'Daisy Rômulo', 'Tufts University', '1986-03-22', 2, 'f', 8],
  [5, 'Ciar Bedwyr', 'George Washington University', '1992-05-29', 13, 'm', 4],
  [6, 'Sarika Asklepios', 'University of Notre Dame', '1994-09-14', 5, 'f', 12],
  [7, 'Katarine Madhav', 'Northwestern University', '1991-08-28', 12, 'f', 4],

  [8, 'Nolan Mieszko', 'Wake Forest University', '1986-10-05', 10, 'm', 11],

  [9, 'Modesto Sanjay', 'Duke University', '1990-08-23', 15, 'm', 10],
  [10, 'Vester Fridtjof', 'Brandeis University', '1986-01-20', 7, 'm', 6],
  [11, 'Kylee Valerius', 'Harvard University', '1985-01-02', 4, 'f', 2],
  [
    12,
    'Colobert Shanon',
    'George Washington University',
    '1992-07-12',
    8,
    'm',
    10,
  ],
  [
    13,
    'Muhammad Hulderic',
    'Franklin and Marshall College',
    '1989-09-19',
    7,
    'm',
    7,
  ],
  [14, 'Philomène Cédric', 'Northwestern University', '1988-01-06', 9, 'f', 1],
  [15, 'Aileen Ezra', 'Southern Methodist University', '1993-08-18', 4, 'f', 5],
];

export const research_Papers = [
  [
    1,
    'Exploring the interplay between full-lifecycle learning design tooling and teacher professional development',
    'Information technology Research',
    '2014-01-18',
    8,
  ],
  [
    2,
    'The psychology of meaningful verbal learning',
    'Information technology Research',
    '2017-12-21',
    4,
  ],
  [
    3,
    'Social web and health research',
    'Information technology Research',
    '2012-11-21',
    7,
  ],
  [
    4,
    'The history of the Chinese Empire over the millennia',
    'History Research',
    '2020-09-24',
    13,
  ],
  [
    5,
    'The rise and fall of Ancient Greek city-states',
    'History Research',
    '2014-10-13',
    3,
  ],
  [
    6,
    'The underlying causes of the World War I',
    'History Research',
    '2020-05-29',
    13,
  ],
  [
    7,
    'Do men and women have different short-term memory mechanisms?',
    'Psychology Research',
    '2014-07-26',
    12,
  ],
  [
    8,
    'Tricking the taste buds: how does smell affect the taste?',
    'Psychology Research',
    '2020-10-31',
    13,
  ],
  [
    9,
    'Is autism a disease or a natural variation of the norm?',
    'Psychology Research',
    '2010-03-15',
    12,
  ],
  [
    10,
    'Eating behaviors in different cultures',
    'Psychology Research',
    '2019-07-17',
    15,
  ],
  [
    11,
    'Differences and similarities in the behavioral patterns of diverse cultures',
    'Psychology Research',
    '2020-01-11',
    7,
  ],
  [
    12,
    'How motivation plays a role in human development',
    'Psychology Research',
    '2014-05-24',
    15,
  ],
  [
    13,
    'An examination of the causes and results of drug and alcohol abuse',
    'Psychology Research',
    '2011-05-13',
    14,
  ],
  [
    14,
    'The impact of music genres on how the brain works',
    'Psychology Research',
    '2021-01-05',
    8,
  ],
  [
    15,
    'Individualized vs. group learning: which is better suited for current reality?',
    'Education Research',
    '2015-11-09',
    7,
  ],
  [
    16,
    'How should the education system approach children with special needs?',
    'Education Research',
    '2017-07-24',
    6,
  ],
  [
    17,
    'Is cheating on tests an expression of an educational failure?',
    'Education Research',
    '2014-11-25',
    7,
  ],
  [
    18,
    'The impact of advertisements and commercials on how people comprehend the world',
    'Business Research',
    '2013-12-08',
    2,
  ],
  [
    19,
    'Social models mass media bestows on teenagers and adults',
    'Social Media Research',
    '2015-03-15',
    13,
  ],
  [
    20,
    'Human dependence on computers: beneficial or harmful',
    'Information technology Research',
    '2013-05-05',
    14,
  ],
  [
    21,
    'Large-scale recycling methods and their effectiveness in reducing waste',
    'Science Research',
    '2018-07-20',
    12,
  ],
  [
    22,
    'People’s impact on climate change: the cost of a technological breakthrough',
    'Science Research',
    '2020-10-01',
    8,
  ],
  [
    23,
    'Strategies for prevention of obesity and associated heart disease risks',
    'Health Research',
    '2016-10-14',
    1,
  ],
  [
    24,
    'Analyze the experiences of children with autism in school and at home',
    'Health Research',
    '2013-10-16',
    11,
  ],
  [25, 'The impact of diet on health', 'Health Research', '2019-05-26', 15],
  [
    26,
    'Social media marketing strategies and the determinants of success',
    'Business Research',
    '2010-01-24',
    5,
  ],
  [27, 'Classic vs modern poetry', 'Literature Research', '2016-03-19', 3],
  [
    28,
    'Culture and literature: which affects which?',
    'Literature Research',
    '2010-11-04',
    15,
  ],
  [
    29,
    'The threat of terrorism in a world without ISIS',
    'Politic Research',
    '2019-04-22',
    9,
  ],
  [30, 'Causes of world hunger', 'Politic Research', '2012-11-22', 14],
];
